# Generated by Django 3.2.2 on 2022-03-06 13:18

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TermsCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=64, verbose_name='title')),
                ('ordering', models.IntegerField()),
            ],
            options={
                'verbose_name': 'terms category',
                'verbose_name_plural': 'terms categories',
                'ordering': ('ordering',),
            },
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=64, verbose_name='title')),
                ('text', tinymce.models.HTMLField(verbose_name='text')),
                ('ordering', models.IntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='terms.termscategory', verbose_name='category')),
            ],
            options={
                'verbose_name': 'term',
                'verbose_name_plural': 'terms',
                'ordering': ('ordering',),
            },
        ),
    ]
